// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftServeTestTask.DAL.Database;

#nullable disable

namespace SoftServeTestTask.DAL.Migrations
{
    [DbContext(typeof(EducationalContext))]
    partial class EducationalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("CourseTeacher", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("TeachersId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("CourseTeacher");
                });

            modelBuilder.Entity("SoftServeTestTask.DAL.Entities.Contacts.StudentContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("StudentContacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 street, house 2",
                            Email = "student1@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 street, house 3",
                            Email = "student2@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 street, house 4",
                            Email = "student3@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 street, house 5",
                            Email = "student4@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 5,
                            Address = "5 street, house 6",
                            Email = "student5@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 6,
                            Address = "6 street, house 7",
                            Email = "student6@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 7,
                            Address = "7 street, house 8",
                            Email = "student7@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 8,
                            Address = "8 street, house 9",
                            Email = "student8@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 9,
                            Address = "9 street, house 10",
                            Email = "student9@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 10,
                            Address = "10 street, house 11",
                            Email = "student10@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 11,
                            Address = "11 street, house 12",
                            Email = "student11@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 12,
                            Address = "12 street, house 13",
                            Email = "student12@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 13,
                            Address = "13 street, house 14",
                            Email = "student13@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 14,
                            Address = "14 street, house 15",
                            Email = "student14@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 15,
                            Address = "15 street, house 16",
                            Email = "student15@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 16,
                            Address = "16 street, house 17",
                            Email = "student16@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 17,
                            Address = "17 street, house 18",
                            Email = "student17@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 18,
                            Address = "18 street, house 19",
                            Email = "student18@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 19,
                            Address = "19 street, house 20",
                            Email = "student19@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 20,
                            Address = "20 street, house 21",
                            Email = "student20@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 21,
                            Address = "21 street, house 22",
                            Email = "student21@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 22,
                            Address = "22 street, house 23",
                            Email = "student22@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 23,
                            Address = "23 street, house 24",
                            Email = "student23@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 24,
                            Address = "24 street, house 25",
                            Email = "student24@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 25,
                            Address = "25 street, house 26",
                            Email = "student25@gmail.com",
                            PhoneNumber = "+380001122334"
                        });
                });

            modelBuilder.Entity("SoftServeTestTask.DAL.Entities.Contacts.TeacherContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("TeacherContacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 street, house 2",
                            Email = "teacher1@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 street, house 3",
                            Email = "teacher2@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 street, house 4",
                            Email = "teacher3@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 street, house 5",
                            Email = "teacher4@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 5,
                            Address = "5 street, house 6",
                            Email = "teacher5@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 6,
                            Address = "6 street, house 7",
                            Email = "teacher6@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 7,
                            Address = "7 street, house 8",
                            Email = "teacher7@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 8,
                            Address = "8 street, house 9",
                            Email = "teacher8@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 9,
                            Address = "9 street, house 10",
                            Email = "teacher9@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 10,
                            Address = "10 street, house 11",
                            Email = "teacher10@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 11,
                            Address = "11 street, house 12",
                            Email = "teacher11@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 12,
                            Address = "12 street, house 13",
                            Email = "teacher12@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 13,
                            Address = "13 street, house 14",
                            Email = "teacher13@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 14,
                            Address = "14 street, house 15",
                            Email = "teacher14@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 15,
                            Address = "15 street, house 16",
                            Email = "teacher15@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 16,
                            Address = "16 street, house 17",
                            Email = "teacher16@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 17,
                            Address = "17 street, house 18",
                            Email = "teacher17@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 18,
                            Address = "18 street, house 19",
                            Email = "teacher18@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 19,
                            Address = "19 street, house 20",
                            Email = "teacher19@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 20,
                            Address = "20 street, house 21",
                            Email = "teacher20@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 21,
                            Address = "21 street, house 22",
                            Email = "teacher21@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 22,
                            Address = "22 street, house 23",
                            Email = "teacher22@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 23,
                            Address = "23 street, house 24",
                            Email = "teacher23@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 24,
                            Address = "24 street, house 25",
                            Email = "teacher24@gmail.com",
                            PhoneNumber = "+380001122334"
                        },
                        new
                        {
                            Id = 25,
                            Address = "25 street, house 26",
                            Email = "teacher25@gmail.com",
                            PhoneNumber = "+380001122334"
                        });
                });

            modelBuilder.Entity("SoftServeTestTask.DAL.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "1 course description",
                            Name = "1 course name"
                        },
                        new
                        {
                            Id = 2,
                            Description = "2 course description",
                            Name = "2 course name"
                        },
                        new
                        {
                            Id = 3,
                            Description = "3 course description",
                            Name = "3 course name"
                        },
                        new
                        {
                            Id = 4,
                            Description = "4 course description",
                            Name = "4 course name"
                        },
                        new
                        {
                            Id = 5,
                            Description = "5 course description",
                            Name = "5 course name"
                        },
                        new
                        {
                            Id = 6,
                            Description = "6 course description",
                            Name = "6 course name"
                        },
                        new
                        {
                            Id = 7,
                            Description = "7 course description",
                            Name = "7 course name"
                        },
                        new
                        {
                            Id = 8,
                            Description = "8 course description",
                            Name = "8 course name"
                        },
                        new
                        {
                            Id = 9,
                            Description = "9 course description",
                            Name = "9 course name"
                        },
                        new
                        {
                            Id = 10,
                            Description = "10 course description",
                            Name = "10 course name"
                        },
                        new
                        {
                            Id = 11,
                            Description = "11 course description",
                            Name = "11 course name"
                        },
                        new
                        {
                            Id = 12,
                            Description = "12 course description",
                            Name = "12 course name"
                        },
                        new
                        {
                            Id = 13,
                            Description = "13 course description",
                            Name = "13 course name"
                        },
                        new
                        {
                            Id = 14,
                            Description = "14 course description",
                            Name = "14 course name"
                        },
                        new
                        {
                            Id = 15,
                            Description = "15 course description",
                            Name = "15 course name"
                        },
                        new
                        {
                            Id = 16,
                            Description = "16 course description",
                            Name = "16 course name"
                        },
                        new
                        {
                            Id = 17,
                            Description = "17 course description",
                            Name = "17 course name"
                        },
                        new
                        {
                            Id = 18,
                            Description = "18 course description",
                            Name = "18 course name"
                        },
                        new
                        {
                            Id = 19,
                            Description = "19 course description",
                            Name = "19 course name"
                        },
                        new
                        {
                            Id = 20,
                            Description = "20 course description",
                            Name = "20 course name"
                        },
                        new
                        {
                            Id = 21,
                            Description = "21 course description",
                            Name = "21 course name"
                        },
                        new
                        {
                            Id = 22,
                            Description = "22 course description",
                            Name = "22 course name"
                        },
                        new
                        {
                            Id = 23,
                            Description = "23 course description",
                            Name = "23 course name"
                        },
                        new
                        {
                            Id = 24,
                            Description = "24 course description",
                            Name = "24 course name"
                        },
                        new
                        {
                            Id = 25,
                            Description = "25 course description",
                            Name = "25 course name"
                        });
                });

            modelBuilder.Entity("SoftServeTestTask.DAL.Entities.Infoes.StudentInfoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("StudentInfoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 19,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3149),
                            FirstName = "Student 1 first name",
                            Gender = "1 gender",
                            SecondName = "Student 1 second name",
                            ThirdName = "Student 1 third name"
                        },
                        new
                        {
                            Id = 2,
                            Age = 20,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3157),
                            FirstName = "Student 2 first name",
                            Gender = "2 gender",
                            SecondName = "Student 2 second name",
                            ThirdName = "Student 2 third name"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3162),
                            FirstName = "Student 3 first name",
                            Gender = "3 gender",
                            SecondName = "Student 3 second name",
                            ThirdName = "Student 3 third name"
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3167),
                            FirstName = "Student 4 first name",
                            Gender = "4 gender",
                            SecondName = "Student 4 second name",
                            ThirdName = "Student 4 third name"
                        },
                        new
                        {
                            Id = 5,
                            Age = 23,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3172),
                            FirstName = "Student 5 first name",
                            Gender = "5 gender",
                            SecondName = "Student 5 second name",
                            ThirdName = "Student 5 third name"
                        },
                        new
                        {
                            Id = 6,
                            Age = 24,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3178),
                            FirstName = "Student 6 first name",
                            Gender = "6 gender",
                            SecondName = "Student 6 second name",
                            ThirdName = "Student 6 third name"
                        },
                        new
                        {
                            Id = 7,
                            Age = 25,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3183),
                            FirstName = "Student 7 first name",
                            Gender = "7 gender",
                            SecondName = "Student 7 second name",
                            ThirdName = "Student 7 third name"
                        },
                        new
                        {
                            Id = 8,
                            Age = 26,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3188),
                            FirstName = "Student 8 first name",
                            Gender = "8 gender",
                            SecondName = "Student 8 second name",
                            ThirdName = "Student 8 third name"
                        },
                        new
                        {
                            Id = 9,
                            Age = 27,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3193),
                            FirstName = "Student 9 first name",
                            Gender = "9 gender",
                            SecondName = "Student 9 second name",
                            ThirdName = "Student 9 third name"
                        },
                        new
                        {
                            Id = 10,
                            Age = 28,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3199),
                            FirstName = "Student 10 first name",
                            Gender = "10 gender",
                            SecondName = "Student 10 second name",
                            ThirdName = "Student 10 third name"
                        },
                        new
                        {
                            Id = 11,
                            Age = 29,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3220),
                            FirstName = "Student 11 first name",
                            Gender = "11 gender",
                            SecondName = "Student 11 second name",
                            ThirdName = "Student 11 third name"
                        },
                        new
                        {
                            Id = 12,
                            Age = 30,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3225),
                            FirstName = "Student 12 first name",
                            Gender = "12 gender",
                            SecondName = "Student 12 second name",
                            ThirdName = "Student 12 third name"
                        },
                        new
                        {
                            Id = 13,
                            Age = 31,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3230),
                            FirstName = "Student 13 first name",
                            Gender = "13 gender",
                            SecondName = "Student 13 second name",
                            ThirdName = "Student 13 third name"
                        },
                        new
                        {
                            Id = 14,
                            Age = 32,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3235),
                            FirstName = "Student 14 first name",
                            Gender = "14 gender",
                            SecondName = "Student 14 second name",
                            ThirdName = "Student 14 third name"
                        },
                        new
                        {
                            Id = 15,
                            Age = 33,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3240),
                            FirstName = "Student 15 first name",
                            Gender = "15 gender",
                            SecondName = "Student 15 second name",
                            ThirdName = "Student 15 third name"
                        },
                        new
                        {
                            Id = 16,
                            Age = 34,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3245),
                            FirstName = "Student 16 first name",
                            Gender = "16 gender",
                            SecondName = "Student 16 second name",
                            ThirdName = "Student 16 third name"
                        },
                        new
                        {
                            Id = 17,
                            Age = 35,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3250),
                            FirstName = "Student 17 first name",
                            Gender = "17 gender",
                            SecondName = "Student 17 second name",
                            ThirdName = "Student 17 third name"
                        },
                        new
                        {
                            Id = 18,
                            Age = 36,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3256),
                            FirstName = "Student 18 first name",
                            Gender = "18 gender",
                            SecondName = "Student 18 second name",
                            ThirdName = "Student 18 third name"
                        },
                        new
                        {
                            Id = 19,
                            Age = 37,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3261),
                            FirstName = "Student 19 first name",
                            Gender = "19 gender",
                            SecondName = "Student 19 second name",
                            ThirdName = "Student 19 third name"
                        },
                        new
                        {
                            Id = 20,
                            Age = 38,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3266),
                            FirstName = "Student 20 first name",
                            Gender = "20 gender",
                            SecondName = "Student 20 second name",
                            ThirdName = "Student 20 third name"
                        },
                        new
                        {
                            Id = 21,
                            Age = 39,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3271),
                            FirstName = "Student 21 first name",
                            Gender = "21 gender",
                            SecondName = "Student 21 second name",
                            ThirdName = "Student 21 third name"
                        },
                        new
                        {
                            Id = 22,
                            Age = 40,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3276),
                            FirstName = "Student 22 first name",
                            Gender = "22 gender",
                            SecondName = "Student 22 second name",
                            ThirdName = "Student 22 third name"
                        },
                        new
                        {
                            Id = 23,
                            Age = 41,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3281),
                            FirstName = "Student 23 first name",
                            Gender = "23 gender",
                            SecondName = "Student 23 second name",
                            ThirdName = "Student 23 third name"
                        },
                        new
                        {
                            Id = 24,
                            Age = 42,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3285),
                            FirstName = "Student 24 first name",
                            Gender = "24 gender",
                            SecondName = "Student 24 second name",
                            ThirdName = "Student 24 third name"
                        },
                        new
                        {
                            Id = 25,
                            Age = 43,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(3290),
                            FirstName = "Student 25 first name",
                            Gender = "25 gender",
                            SecondName = "Student 25 second name",
                            ThirdName = "Student 25 third name"
                        });
                });

            modelBuilder.Entity("SoftServeTestTask.DAL.Entities.Infoes.TeacherInfoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("TeachersInfoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 31,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2750),
                            FirstName = "Teacher 1 first name",
                            Gender = "1 gender",
                            SecondName = "Teacher 1 second name",
                            ThirdName = "Teacher 1 third name"
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2810),
                            FirstName = "Teacher 2 first name",
                            Gender = "2 gender",
                            SecondName = "Teacher 2 second name",
                            ThirdName = "Teacher 2 third name"
                        },
                        new
                        {
                            Id = 3,
                            Age = 33,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2815),
                            FirstName = "Teacher 3 first name",
                            Gender = "3 gender",
                            SecondName = "Teacher 3 second name",
                            ThirdName = "Teacher 3 third name"
                        },
                        new
                        {
                            Id = 4,
                            Age = 34,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2820),
                            FirstName = "Teacher 4 first name",
                            Gender = "4 gender",
                            SecondName = "Teacher 4 second name",
                            ThirdName = "Teacher 4 third name"
                        },
                        new
                        {
                            Id = 5,
                            Age = 35,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2825),
                            FirstName = "Teacher 5 first name",
                            Gender = "5 gender",
                            SecondName = "Teacher 5 second name",
                            ThirdName = "Teacher 5 third name"
                        },
                        new
                        {
                            Id = 6,
                            Age = 36,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2831),
                            FirstName = "Teacher 6 first name",
                            Gender = "6 gender",
                            SecondName = "Teacher 6 second name",
                            ThirdName = "Teacher 6 third name"
                        },
                        new
                        {
                            Id = 7,
                            Age = 37,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2836),
                            FirstName = "Teacher 7 first name",
                            Gender = "7 gender",
                            SecondName = "Teacher 7 second name",
                            ThirdName = "Teacher 7 third name"
                        },
                        new
                        {
                            Id = 8,
                            Age = 38,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2841),
                            FirstName = "Teacher 8 first name",
                            Gender = "8 gender",
                            SecondName = "Teacher 8 second name",
                            ThirdName = "Teacher 8 third name"
                        },
                        new
                        {
                            Id = 9,
                            Age = 39,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2846),
                            FirstName = "Teacher 9 first name",
                            Gender = "9 gender",
                            SecondName = "Teacher 9 second name",
                            ThirdName = "Teacher 9 third name"
                        },
                        new
                        {
                            Id = 10,
                            Age = 40,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2852),
                            FirstName = "Teacher 10 first name",
                            Gender = "10 gender",
                            SecondName = "Teacher 10 second name",
                            ThirdName = "Teacher 10 third name"
                        },
                        new
                        {
                            Id = 11,
                            Age = 41,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2857),
                            FirstName = "Teacher 11 first name",
                            Gender = "11 gender",
                            SecondName = "Teacher 11 second name",
                            ThirdName = "Teacher 11 third name"
                        },
                        new
                        {
                            Id = 12,
                            Age = 42,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2862),
                            FirstName = "Teacher 12 first name",
                            Gender = "12 gender",
                            SecondName = "Teacher 12 second name",
                            ThirdName = "Teacher 12 third name"
                        },
                        new
                        {
                            Id = 13,
                            Age = 43,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2892),
                            FirstName = "Teacher 13 first name",
                            Gender = "13 gender",
                            SecondName = "Teacher 13 second name",
                            ThirdName = "Teacher 13 third name"
                        },
                        new
                        {
                            Id = 14,
                            Age = 44,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2898),
                            FirstName = "Teacher 14 first name",
                            Gender = "14 gender",
                            SecondName = "Teacher 14 second name",
                            ThirdName = "Teacher 14 third name"
                        },
                        new
                        {
                            Id = 15,
                            Age = 45,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2903),
                            FirstName = "Teacher 15 first name",
                            Gender = "15 gender",
                            SecondName = "Teacher 15 second name",
                            ThirdName = "Teacher 15 third name"
                        },
                        new
                        {
                            Id = 16,
                            Age = 46,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2908),
                            FirstName = "Teacher 16 first name",
                            Gender = "16 gender",
                            SecondName = "Teacher 16 second name",
                            ThirdName = "Teacher 16 third name"
                        },
                        new
                        {
                            Id = 17,
                            Age = 47,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2913),
                            FirstName = "Teacher 17 first name",
                            Gender = "17 gender",
                            SecondName = "Teacher 17 second name",
                            ThirdName = "Teacher 17 third name"
                        },
                        new
                        {
                            Id = 18,
                            Age = 48,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2919),
                            FirstName = "Teacher 18 first name",
                            Gender = "18 gender",
                            SecondName = "Teacher 18 second name",
                            ThirdName = "Teacher 18 third name"
                        },
                        new
                        {
                            Id = 19,
                            Age = 49,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2924),
                            FirstName = "Teacher 19 first name",
                            Gender = "19 gender",
                            SecondName = "Teacher 19 second name",
                            ThirdName = "Teacher 19 third name"
                        },
                        new
                        {
                            Id = 20,
                            Age = 50,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2929),
                            FirstName = "Teacher 20 first name",
                            Gender = "20 gender",
                            SecondName = "Teacher 20 second name",
                            ThirdName = "Teacher 20 third name"
                        },
                        new
                        {
                            Id = 21,
                            Age = 51,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2934),
                            FirstName = "Teacher 21 first name",
                            Gender = "21 gender",
                            SecondName = "Teacher 21 second name",
                            ThirdName = "Teacher 21 third name"
                        },
                        new
                        {
                            Id = 22,
                            Age = 52,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2939),
                            FirstName = "Teacher 22 first name",
                            Gender = "22 gender",
                            SecondName = "Teacher 22 second name",
                            ThirdName = "Teacher 22 third name"
                        },
                        new
                        {
                            Id = 23,
                            Age = 53,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2944),
                            FirstName = "Teacher 23 first name",
                            Gender = "23 gender",
                            SecondName = "Teacher 23 second name",
                            ThirdName = "Teacher 23 third name"
                        },
                        new
                        {
                            Id = 24,
                            Age = 54,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2949),
                            FirstName = "Teacher 24 first name",
                            Gender = "24 gender",
                            SecondName = "Teacher 24 second name",
                            ThirdName = "Teacher 24 third name"
                        },
                        new
                        {
                            Id = 25,
                            Age = 55,
                            BirthDate = new DateTime(2024, 5, 29, 16, 35, 18, 761, DateTimeKind.Local).AddTicks(2954),
                            FirstName = "Teacher 25 first name",
                            Gender = "25 gender",
                            SecondName = "Teacher 25 second name",
                            ThirdName = "Teacher 25 third name"
                        });
                });

            modelBuilder.Entity("SoftServeTestTask.DAL.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactsId")
                        .HasColumnType("int");

                    b.Property<decimal>("GPA")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("InfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactsId")
                        .IsUnique();

                    b.HasIndex("InfoId")
                        .IsUnique();

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactsId = 1,
                            GPA = 4.39946361486951m,
                            Group = "1 student group",
                            InfoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContactsId = 2,
                            GPA = 3.95830992712239m,
                            Group = "2 student group",
                            InfoId = 2
                        },
                        new
                        {
                            Id = 3,
                            ContactsId = 3,
                            GPA = 3.41656179618226m,
                            Group = "3 student group",
                            InfoId = 3
                        },
                        new
                        {
                            Id = 4,
                            ContactsId = 4,
                            GPA = 4.21644152362661m,
                            Group = "4 student group",
                            InfoId = 4
                        },
                        new
                        {
                            Id = 5,
                            ContactsId = 5,
                            GPA = 4.41139091002224m,
                            Group = "5 student group",
                            InfoId = 5
                        },
                        new
                        {
                            Id = 6,
                            ContactsId = 6,
                            GPA = 4.67222811402902m,
                            Group = "6 student group",
                            InfoId = 6
                        },
                        new
                        {
                            Id = 7,
                            ContactsId = 7,
                            GPA = 4.69012031106494m,
                            Group = "7 student group",
                            InfoId = 7
                        },
                        new
                        {
                            Id = 8,
                            ContactsId = 8,
                            GPA = 4.42230886963679m,
                            Group = "8 student group",
                            InfoId = 8
                        },
                        new
                        {
                            Id = 9,
                            ContactsId = 9,
                            GPA = 3.13993533679127m,
                            Group = "9 student group",
                            InfoId = 9
                        },
                        new
                        {
                            Id = 10,
                            ContactsId = 10,
                            GPA = 4.20548640980008m,
                            Group = "10 student group",
                            InfoId = 10
                        },
                        new
                        {
                            Id = 11,
                            ContactsId = 11,
                            GPA = 3.32415540778736m,
                            Group = "11 student group",
                            InfoId = 11
                        },
                        new
                        {
                            Id = 12,
                            ContactsId = 12,
                            GPA = 4.40205955065281m,
                            Group = "12 student group",
                            InfoId = 12
                        },
                        new
                        {
                            Id = 13,
                            ContactsId = 13,
                            GPA = 3.55284794449529m,
                            Group = "13 student group",
                            InfoId = 13
                        },
                        new
                        {
                            Id = 14,
                            ContactsId = 14,
                            GPA = 3.22907175912146m,
                            Group = "14 student group",
                            InfoId = 14
                        },
                        new
                        {
                            Id = 15,
                            ContactsId = 15,
                            GPA = 4.71708973626318m,
                            Group = "15 student group",
                            InfoId = 15
                        },
                        new
                        {
                            Id = 16,
                            ContactsId = 16,
                            GPA = 4.98728315948691m,
                            Group = "16 student group",
                            InfoId = 16
                        },
                        new
                        {
                            Id = 17,
                            ContactsId = 17,
                            GPA = 3.14275385818266m,
                            Group = "17 student group",
                            InfoId = 17
                        },
                        new
                        {
                            Id = 18,
                            ContactsId = 18,
                            GPA = 3.8072699242196m,
                            Group = "18 student group",
                            InfoId = 18
                        },
                        new
                        {
                            Id = 19,
                            ContactsId = 19,
                            GPA = 4.68863352862479m,
                            Group = "19 student group",
                            InfoId = 19
                        },
                        new
                        {
                            Id = 20,
                            ContactsId = 20,
                            GPA = 4.46710510721084m,
                            Group = "20 student group",
                            InfoId = 20
                        },
                        new
                        {
                            Id = 21,
                            ContactsId = 21,
                            GPA = 3.42166814674025m,
                            Group = "21 student group",
                            InfoId = 21
                        },
                        new
                        {
                            Id = 22,
                            ContactsId = 22,
                            GPA = 3.10086330575528m,
                            Group = "22 student group",
                            InfoId = 22
                        },
                        new
                        {
                            Id = 23,
                            ContactsId = 23,
                            GPA = 3.64849786346548m,
                            Group = "23 student group",
                            InfoId = 23
                        },
                        new
                        {
                            Id = 24,
                            ContactsId = 24,
                            GPA = 4.79349656500742m,
                            Group = "24 student group",
                            InfoId = 24
                        },
                        new
                        {
                            Id = 25,
                            ContactsId = 25,
                            GPA = 4.30885863712004m,
                            Group = "25 student group",
                            InfoId = 25
                        });
                });

            modelBuilder.Entity("SoftServeTestTask.DAL.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicDegree")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("ContactsId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("InfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactsId")
                        .IsUnique();

                    b.HasIndex("InfoId")
                        .IsUnique();

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicDegree = "1 degree",
                            ContactsId = 1,
                            ExperienceYears = 2,
                            InfoId = 1
                        },
                        new
                        {
                            Id = 2,
                            AcademicDegree = "2 degree",
                            ContactsId = 2,
                            ExperienceYears = 4,
                            InfoId = 2
                        },
                        new
                        {
                            Id = 3,
                            AcademicDegree = "3 degree",
                            ContactsId = 3,
                            ExperienceYears = 6,
                            InfoId = 3
                        },
                        new
                        {
                            Id = 4,
                            AcademicDegree = "4 degree",
                            ContactsId = 4,
                            ExperienceYears = 8,
                            InfoId = 4
                        },
                        new
                        {
                            Id = 5,
                            AcademicDegree = "5 degree",
                            ContactsId = 5,
                            ExperienceYears = 10,
                            InfoId = 5
                        },
                        new
                        {
                            Id = 6,
                            AcademicDegree = "6 degree",
                            ContactsId = 6,
                            ExperienceYears = 12,
                            InfoId = 6
                        },
                        new
                        {
                            Id = 7,
                            AcademicDegree = "7 degree",
                            ContactsId = 7,
                            ExperienceYears = 14,
                            InfoId = 7
                        },
                        new
                        {
                            Id = 8,
                            AcademicDegree = "8 degree",
                            ContactsId = 8,
                            ExperienceYears = 16,
                            InfoId = 8
                        },
                        new
                        {
                            Id = 9,
                            AcademicDegree = "9 degree",
                            ContactsId = 9,
                            ExperienceYears = 18,
                            InfoId = 9
                        },
                        new
                        {
                            Id = 10,
                            AcademicDegree = "10 degree",
                            ContactsId = 10,
                            ExperienceYears = 20,
                            InfoId = 10
                        },
                        new
                        {
                            Id = 11,
                            AcademicDegree = "11 degree",
                            ContactsId = 11,
                            ExperienceYears = 22,
                            InfoId = 11
                        },
                        new
                        {
                            Id = 12,
                            AcademicDegree = "12 degree",
                            ContactsId = 12,
                            ExperienceYears = 24,
                            InfoId = 12
                        },
                        new
                        {
                            Id = 13,
                            AcademicDegree = "13 degree",
                            ContactsId = 13,
                            ExperienceYears = 26,
                            InfoId = 13
                        },
                        new
                        {
                            Id = 14,
                            AcademicDegree = "14 degree",
                            ContactsId = 14,
                            ExperienceYears = 28,
                            InfoId = 14
                        },
                        new
                        {
                            Id = 15,
                            AcademicDegree = "15 degree",
                            ContactsId = 15,
                            ExperienceYears = 30,
                            InfoId = 15
                        },
                        new
                        {
                            Id = 16,
                            AcademicDegree = "16 degree",
                            ContactsId = 16,
                            ExperienceYears = 32,
                            InfoId = 16
                        },
                        new
                        {
                            Id = 17,
                            AcademicDegree = "17 degree",
                            ContactsId = 17,
                            ExperienceYears = 34,
                            InfoId = 17
                        },
                        new
                        {
                            Id = 18,
                            AcademicDegree = "18 degree",
                            ContactsId = 18,
                            ExperienceYears = 36,
                            InfoId = 18
                        },
                        new
                        {
                            Id = 19,
                            AcademicDegree = "19 degree",
                            ContactsId = 19,
                            ExperienceYears = 38,
                            InfoId = 19
                        },
                        new
                        {
                            Id = 20,
                            AcademicDegree = "20 degree",
                            ContactsId = 20,
                            ExperienceYears = 40,
                            InfoId = 20
                        },
                        new
                        {
                            Id = 21,
                            AcademicDegree = "21 degree",
                            ContactsId = 21,
                            ExperienceYears = 42,
                            InfoId = 21
                        },
                        new
                        {
                            Id = 22,
                            AcademicDegree = "22 degree",
                            ContactsId = 22,
                            ExperienceYears = 44,
                            InfoId = 22
                        },
                        new
                        {
                            Id = 23,
                            AcademicDegree = "23 degree",
                            ContactsId = 23,
                            ExperienceYears = 46,
                            InfoId = 23
                        },
                        new
                        {
                            Id = 24,
                            AcademicDegree = "24 degree",
                            ContactsId = 24,
                            ExperienceYears = 48,
                            InfoId = 24
                        },
                        new
                        {
                            Id = 25,
                            AcademicDegree = "25 degree",
                            ContactsId = 25,
                            ExperienceYears = 50,
                            InfoId = 25
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("SoftServeTestTask.DAL.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftServeTestTask.DAL.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseTeacher", b =>
                {
                    b.HasOne("SoftServeTestTask.DAL.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftServeTestTask.DAL.Entities.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoftServeTestTask.DAL.Entities.Student", b =>
                {
                    b.HasOne("SoftServeTestTask.DAL.Entities.Contacts.StudentContacts", "Contacts")
                        .WithOne()
                        .HasForeignKey("SoftServeTestTask.DAL.Entities.Student", "ContactsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftServeTestTask.DAL.Entities.Infoes.StudentInfoes", "Info")
                        .WithOne()
                        .HasForeignKey("SoftServeTestTask.DAL.Entities.Student", "InfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacts");

                    b.Navigation("Info");
                });

            modelBuilder.Entity("SoftServeTestTask.DAL.Entities.Teacher", b =>
                {
                    b.HasOne("SoftServeTestTask.DAL.Entities.Contacts.TeacherContacts", "Contacts")
                        .WithOne()
                        .HasForeignKey("SoftServeTestTask.DAL.Entities.Teacher", "ContactsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftServeTestTask.DAL.Entities.Infoes.TeacherInfoes", "Info")
                        .WithOne()
                        .HasForeignKey("SoftServeTestTask.DAL.Entities.Teacher", "InfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacts");

                    b.Navigation("Info");
                });
#pragma warning restore 612, 618
        }
    }
}
